services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 5000:5000
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      SECRET_KEY: my-secret-key
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
